name: build-extension
nodes:
  - id: start
    type: start
    position:
      x: 120
      'y': -60
  - id: agent_1
    type: agent
    position:
      x: 290
      'y': 330
    data:
      agent: builder
      prompt: Build the VSC extension
      model: qwen3.6-27b
      timeout: 300
      retries: 3
  - id: end_2
    type: end
    position:
      x: 580
      'y': 640
    data:
      label: End
      summary: true
  - id: agent_3
    type: agent
    position:
      x: 110
      'y': 40
    data:
      agent: implementer
      prompt: implement feature
      model: qwen3.6-27b
      timeout: 300
      retries: 0
  - id: condition_6
    type: condition
    position:
      x: 110
      'y': 200
    data:
      prompt: Sanity check the the previous agent worked the issue provided to the workflow.
      model: qwen3.6-27b
  - id: note_10
    type: note
    position:
      x: 690
      'y': -30
    data:
      text: Remove Note header, note should only have body.
      description: ''
  - id: process_11
    type: process
    position:
      x: 270
      'y': 680
    data:
      title: michel tests extension by reloading VSC
      description: ''
  - id: note_12
    type: note
    position:
      x: 860
      'y': 220
    data:
      text: Double the height of the condition node
      description: ''
  - id: note_13
    type: note
    position:
      x: 820
      'y': 80
    data:
      text: The Condition times out too quickly, increase the note timeout.
      description: ''
  - id: note_14
    type: note
    position:
      x: 510
      'y': 100
    data:
      text: Feature, review last workflow execution log, identify issue, and fix error if there are any.
      description: ''
  - id: process_15
    type: process
    position:
      x: 320
      'y': 810
    data:
      title: Michel prompts agent in chat to review last execution logs and fix issues.
      description: ''
  - id: note_16
    type: note
    position:
      x: 480
      'y': 190
    data:
      text: 'Feature: factory, a canvas that shows all workflows, can execute one or more workflows in parallel.'
      description: ''
  - id: note_17
    type: note
    position:
      x: 440
      'y': -30
    data:
      text: Feature, exception handling, route to fix last execution agent.
      description: ''
  - id: note_18
    type: note
    position:
      x: 580
      'y': 290
    data:
      text: Build a feature refining loop that goes into a grill me session
      description: ''
  - id: note_19
    type: note
    position:
      x: 530
      'y': 420
    data:
      text: add quality checks agent followed by a verifier
      description: ''
  - id: condition_20
    type: condition
    position:
      x: 340
      'y': 490
    data:
      prompt: Return false if the build failed, true otherwise.
      model: qwen3.6-27b
  - id: note_21
    type: note
    position:
      x: 820
      'y': 350
    data:
      text: Note text here
      description: ''
edges:
  - source: start
    target: agent_3
    sourceSide: bottom
    targetSide: top
  - source: agent_3
    target: condition_6
    sourceSide: bottom
    targetSide: top
  - source: condition_6
    target: agent_1
    label: 'True'
    sourceSide: right
    targetSide: top
  - source: condition_6
    target: agent_3
    label: 'False'
    sourceSide: left
    targetSide: left
  - source: condition_20
    target: agent_1
    label: 'False'
    sourceSide: left
    targetSide: left
  - source: condition_20
    target: end_2
    label: 'True'
    sourceSide: right
    targetSide: left
  - source: agent_1
    target: condition_20
    sourceSide: bottom
    targetSide: top
description: A new workflow
