name: test-loop
nodes:
  - id: start_1
    type: start
    position:
      x: 300
      'y': 20
    data:
      label: Start
  - id: agent_11
    type: agent
    position:
      x: 370
      'y': 110
    data:
      agent: tester
      prompt: return state.results = false if your random number generate returns a number less than 5 when you execute random() % 10
      model: qwen3.6-27b
      timeout: 120
      retries: 0
  - id: end_13
    type: end
    position:
      x: 590
      'y': 160
    data:
      label: End
  - id: condition_14
    type: condition
    position:
      x: 300
      'y': 300
    data:
      expression: state.result === true
edges:
  - source: start_1
    target: agent_11
  - source: condition_14
    target: end_13
  - source: condition_14
    target: agent_11
description: Workflow with a retry loop - Implement → Test → Pass? → loop back or complete
